const excuses = [
  "Jeg skal sannsynligvis forsove meg",
  "Jeg skal feire 8-årsdagen til hunden til dama til broren til klassekameraten min fra 7.klasse",
  "Jeg mangler sosiale evner",
  "Det skal regne",
  "Jeg lovte en venn å fikse toalettet sitt. Han er redd for å gjøre det alene fordi han har drittfobi",
  "Kompisa dine hater meg",
  "Jeg får besøk av presidenten",
  "Jeg må hjem og mate alpakkaen",
  "Melken min går ut på dato",
  "Jeg skal til gynekologen",
  "Min spådame frarådet meg å forlate hjemme",
  "Jeg har mensen",
  "Jeg må trøste venninna mi som har blitt dumpet av en utro jævel",
  "House of the Dragons har sesongavslutning i kveld!!!",
  "Jeg skulle ut men så kom jeg på at jeg manglet melk og det er snart søndag så jeg måtte på butikken hvor jeg så en hund som så skadet ut så jeg tok den med til dyrlegen og fant så eieren etter at den ble fikset, så måtte jeg løpe til butikken igjen og der ble jeg ranet på veien så jeg måtte hjem for å hente mer penger hvor jeg så havnet i slagsmål med en full matros. Han knocket meg ut og så våknet jeg nå og rakk ikke avtalen… Kan jeg låne melk?",
  "Hunden min har diare",
  "Jeg hadde pizza og øl med jobben i går",
];
